#!/bin/sh
EXPR='(ss-eval-expr
"(let ((outs (make-array 0 :element-type '\''character :fill-pointer 0 :adjustable t)))
  (with-output-to-string (s outs)
  (let ((*error-output* s)
        (*standard-output* s))
    (multiple-value-bind (truename warnings-p failure-p)
        (compile-file \"'"$1"'\")
        (unless failure-p
          (load truename))
          (finish-output s)
          (values (not failure-p) outs)))))")'
#echo "$EXPR" >&2
OUTPUT="$(emacsclient -s slime-server -e "$EXPR")" 
printf "%b" "$OUTPUT" >&2

printf "%s" $OUTPUT|grep -q '^(("T"'
